foodflow:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: foodflow
    username: root
    password: kinki2arashi5

  redis:
    host: localhost
    port: 6379
    database: 0
    password: root@123456