server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
      driver-class-name: ${foodflow.datasource.driver-class-name}
      #url: jdbc:mysql://${foodflow.datasource.host}:${foodflow.datasource.port}/${foodflow.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      url: jdbc:mysql://${foodflow.datasource.host}:${foodflow.datasource.port}/${foodflow.datasource.database}
      username: ${foodflow.datasource.username}
      password: ${foodflow.datasource.password}
      type: com.alibaba.druid.pool.DruidDataSource
  data:
    redis:
      host: ${foodflow.redis.host}
      port: ${foodflow.redis.port}
      database: ${foodflow.redis.database}
      password: ${foodflow.redis.password}

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.foodflow.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.foodflow.controller

logging:
  level:
    com:
      foodflow:
        mapper: debug
        service: info
        controller: info

foodflow:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
  salt: "foodflowjavaapplicationprojectforpractice"

